#test case 1
print("Selamat datang di kalkulator sederhana")
print("ketik 1 untuk menghitung penjumlahan.")
print("ketik 2 untuk menghitung pengurangan.")
print("ketik 3 untuk menghitung perkalian.")
print("ketik 4 untuk menghitung pembagian.")
print("ketik 5 untuk menghitung sisa hasil bagi(modulus)")
print("ketik 6 untuk menghitung pemangkatan")
n = input("masukkan pilihan anda: ")
t = input("masukkan bilangan pertama: ")
r = input("masukkan bilangan kedua: ")
print("hasil dari" ,t, "dijumlahkan dengan" ,r, "adalah" )

#test case 2
print("Selamat datang di kalkulator sederhana")
print("ketik 1 untuk menghitung penjumlahan.")
print("ketik 2 untuk menghitung pengurangan.")
print("ketik 3 untuk menghitung perkalian.")
print("ketik 4 untuk menghitung pembagian.")
print("ketik 5 untuk menghitung sisa hasil bagi(modulus)")
print("ketik 6 untuk menghitung pemangkatan")
n = input("masukkan pilihan anda: ")
t = input("masukkan bilangan pertama: ")
r = input("masukkan bilangan kedua: ")
print("hasil dari" ,t, "dikurangi dengan" ,r, "adalah" )

#test case 3
print("Selamat datang di kalkulator sederhana")
print("ketik 1 untuk menghitung penjumlahan.")
print("ketik 2 untuk menghitung pengurangan.")
print("ketik 3 untuk menghitung perkalian.")
print("ketik 4 untuk menghitung pembagian.")
print("ketik 5 untuk menghitung sisa hasil bagi(modulus)")
print("ketik 6 untuk menghitung pemangkatan")
n = input("masukkan pilihan anda: ")
t = input("masukkan bilangan pertama: ")
r = input("masukkan bilangan kedua: ")
print("hasil dari" ,t, "dikali dengan" ,r, "adalah" )

#test case 4
print("Selamat datang di kalkulator sederhana")
print("ketik 1 untuk menghitung penjumlahan.")
print("ketik 2 untuk menghitung pengurangan.")
print("ketik 3 untuk menghitung perkalian.")
print("ketik 4 untuk menghitung pembagian.")
print("ketik 5 untuk menghitung sisa hasil bagi(modulus)")
print("ketik 6 untuk menghitung pemangkatan")
n = input("masukkan pilihan anda: ")
t = input("masukkan bilangan pertama: ")
r = input("masukkan bilangan kedua: ")
print("hasil dari" ,t, "dibagi dengan" ,r, "adalah" )

#test case 5
print("Selamat datang di kalkulator sederhana")
print("ketik 1 untuk menghitung penjumlahan.")
print("ketik 2 untuk menghitung pengurangan.")
print("ketik 3 untuk menghitung perkalian.")
print("ketik 4 untuk menghitung pembagian.")
print("ketik 5 untuk menghitung sisa hasil bagi(modulus)")
print("ketik 6 untuk menghitung pemangkatan")
n = input("masukkan pilihan anda: ")
t = input("masukkan bilangan pertama: ")
r = input("masukkan bilangan kedua: ")
print("hasil dari" ,t, "sisa hasil dengan" ,r, "adalah" )

#test case 6
print("Selamat datang di kalkulator sederhana")
print("ketik 1 untuk menghitung penjumlahan.")
print("ketik 2 untuk menghitung pengurangan.")
print("ketik 3 untuk menghitung perkalian.")
print("ketik 4 untuk menghitung pembagian.")
print("ketik 5 untuk menghitung sisa hasil bagi(modulus)")
print("ketik 6 untuk menghitung pemangkatan")
n = input("masukkan pilihan anda: ")
t = input("masukkan bilangan pertama: ")
r = input("masukkan bilangan kedua: ")
print("hasil dari" ,t, "dipangkatkan dengan" ,r, "adalah" )